spring:
  application:
     name: user-service
server:
  port: 8082
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
#Use below property if you are using eureka
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#@EnableDiscoveryClient -> Add this in mainclass if eureka is enabled
